### ISSUE TITLE
Bat deleted if TPed

### ISSUE THREAD

**Issue by srnyx** [Fulmineo64/CompanionBats#6] opened 2021-04-25 19:54 UTC
If the player teleports away, the bat and the bat flute will be deleted.
This is really annoying on my server because we use homes and /tpa.
Instead of it getting deleted, maybe it could just be called back into the player's inventory?

**Comment by Fulmineo64** [comment] 2021-05-02 18:15
Hi, 
I noticed that tp-ing normally doesn't do this.

Does this happen because your server has multiple worlds / maps that you can teleport to?
If that's the case your bat should be fine where you left it. If you find it again you can re-tame it with some pumpkin pies.

Anyway if that's the cause of your issue I have a possible solution in mind, 
I will try to implement it as soon as you give a confirmation on the matter.

Thank you.

**Comment by Fulmineo64** [comment] 2021-05-20 18:28
Hi,
the latest Fabric version should resolve this problem even if you get teleported in another world / dimension.

I'm closing this issue for now, but feel free to re-open it if this last change doesn't solve your problem.
See ya!

**Closed as completed by Fulmineo64** 2021-05-20 18:28 UTC
